"""
Startup Installer for Smart Scheduler
Automatically configures Windows to start your scheduler on boot
"""

import os
import sys
import shutil
from pathlib import Path
import subprocess

def get_startup_folder():
    """Get the Windows startup folder path"""
    startup_folder = Path(os.environ['APPDATA']) / 'Microsoft' / 'Windows' / 'Start Menu' / 'Programs' / 'Startup'
    return startup_folder

def create_startup_batch(script_dir, venv_path=None):
    """Create a batch file for startup"""
    
    batch_content = f"""@echo off
REM Auto-start Weekly Python Scheduler
REM Generated by startup_installer.py

title Weekly Python Scheduler
echo Starting Weekly Python Scheduler...

REM Change to scheduler directory
cd /d "{script_dir}"

"""
    
    if venv_path:
        # Check if it's a conda environment
        if "envs" in venv_path or "miniconda" in venv_path.lower() or "anaconda" in venv_path.lower():
            env_name = Path(venv_path).name
            # Get conda base path and python executable
            conda_base = str(Path(venv_path).parent.parent)
            python_exe = f"{venv_path}\\python.exe"
            batch_content += f"""REM Use conda environment python directly
set PYTHON_EXE={python_exe}
set PYTHONIOENCODING=utf-8
if not exist "%PYTHON_EXE%" (
    echo ERROR: Python not found at %PYTHON_EXE%
    timeout /t 30
    exit /b 1
)

"""
        else:
            # Regular virtual environment
            batch_content += f"""REM Activate virtual environment
call "{venv_path}\\Scripts\\activate.bat"
if errorlevel 1 (
    echo ERROR: Failed to activate virtual environment
    echo Path: {venv_path}
    timeout /t 30
    exit /b 1
)


"""
    
    # Determine which python command to use
    python_cmd = '"%PYTHON_EXE%"' if venv_path and ("envs" in venv_path or "miniconda" in venv_path.lower() or "anaconda" in venv_path.lower()) else "python"
    
    batch_content += f"""REM Start the scheduler with auto-restart
:start
echo Starting scheduler at %date% %time%
{python_cmd} smart_scheduler.py

REM If scheduler exits, wait and restart
echo Scheduler stopped at %date% %time%
echo Restarting in 30 seconds... (Press Ctrl+C to stop)
timeout /t 30 /nobreak >nul
goto start
"""
    
    return batch_content

def install_to_startup():
    """Install the scheduler to Windows startup"""
    print("🚀 Installing Weekly Scheduler to Windows Startup")
    print("=" * 50)
    
    # Get current directory
    current_dir = Path.cwd().absolute()
    print(f"📁 Scheduler directory: {current_dir}")
    
    # Check if smart_scheduler.py exists
    scheduler_file = current_dir / "smart_scheduler.py"
    if not scheduler_file.exists():
        print("❌ smart_scheduler.py not found in current directory")
        print("Please run this script from the same folder as smart_scheduler.py")
        input("Press Enter to exit...")
        return False
    
    # Get virtual environment path from smart_scheduler.py
    venv_path = None
    try:
        with open(scheduler_file, 'r') as f:
            content = f.read()
            for line in content.split('\n'):
                if line.strip().startswith('VENV_PATH = r"') and 'C:\\path\\to\\your\\venv' not in line:
                    venv_path = line.split('r"')[1].split('"')[0]
                    break
        
        if venv_path and venv_path != "C:\\path\\to\\your\\venv":
            print(f"🐍 Virtual environment: {venv_path}")
            if not Path(venv_path).exists():
                print(f"⚠️  Warning: Virtual environment not found at {venv_path}")
        else:
            print("⚠️  Virtual environment not configured in smart_scheduler.py")
            venv_path = None
    except Exception as e:
        print(f"⚠️  Could not read virtual environment from smart_scheduler.py: {e}")
        venv_path = None
    
    # Get startup folder
    startup_folder = get_startup_folder()
    print(f"📂 Startup folder: {startup_folder}")
    
    if not startup_folder.exists():
        print("❌ Windows startup folder not found")
        return False
    
    # Create batch file content
    batch_content = create_startup_batch(str(current_dir), venv_path)
    
    # Write batch file to startup folder
    batch_file = startup_folder / "WeeklyScheduler.bat"
    try:
        with open(batch_file, 'w') as f:
            f.write(batch_content)
        
        print(f"✅ Startup batch file created: {batch_file}")
        print("\n🎉 Installation Complete!")
        print("=" * 30)
        print("Your Weekly Scheduler will now start automatically when Windows boots.")
        print()
        print("What happens on startup:")
        print("1. Windows starts")
        print("2. Batch file runs automatically")
        print("3. Virtual environment activates (if configured)")
        print("4. Scheduler starts and waits for weekly execution")
        print("5. If scheduler crashes, it automatically restarts")
        
        return True
        
    except Exception as e:
        print(f"❌ Failed to create startup file: {e}")
        return False

def uninstall_from_startup():
    """Remove the scheduler from Windows startup"""
    startup_folder = get_startup_folder()
    batch_file = startup_folder / "WeeklyScheduler.bat"
    
    if batch_file.exists():
        try:
            batch_file.unlink()
            print("✅ Scheduler removed from Windows startup")
            return True
        except Exception as e:
            print(f"❌ Failed to remove startup file: {e}")
            return False
    else:
        print("ℹ️  Scheduler not found in startup folder")
        return True

def create_task_scheduler_command():
    """Generate Windows Task Scheduler command"""
    current_dir = Path.cwd().absolute()
    
    # Try to find Python executable
    python_exe = sys.executable
    
    print(f"\n📋 Windows Task Scheduler Command:")
    print("Copy and paste this command in Command Prompt (Run as Administrator):")
    print("-" * 70)
    
    command = f'''schtasks /create /tn "WeeklyPythonScheduler" /tr "\\"{python_exe}\\" \\"{current_dir}\\smart_scheduler.py\\"" /sc onstart /ru SYSTEM /rl HIGHEST /f'''
    
    print(command)
    print("-" * 70)
    print("This creates a system-level task that starts with Windows")

def main():
    """Main installation menu"""
    print("🔧 Weekly Scheduler Startup Configuration")
    print("=" * 45)
    print("Choose how to start your scheduler automatically:")
    print()
    print("1. Install to Windows Startup Folder (Recommended)")
    print("2. Generate Task Scheduler Command")
    print("3. Remove from Startup")
    print("4. Exit")
    
    while True:
        choice = input("\nEnter your choice (1-4): ").strip()
        
        if choice == "1":
            if install_to_startup():
                print("\n💡 Tips:")
                print("- Test by restarting your computer")
                print("- Check Task Manager > Startup tab to see the entry")
                print("- The scheduler will run in a console window")
                print("- To stop it, close the console window or use Ctrl+C")
            break
            
        elif choice == "2":
            create_task_scheduler_command()
            print("\n💡 After running the command:")
            print("- Open Task Scheduler (taskschd.msc)")
            print("- Find 'WeeklyPythonScheduler' task")
            print("- Right-click > Properties to modify settings")
            break
            
        elif choice == "3":
            if uninstall_from_startup():
                print("The scheduler will no longer start automatically")
            break
            
        elif choice == "4":
            print("Goodbye!")
            break
            
        else:
            print("Invalid choice. Please enter 1, 2, 3, or 4.")
    
    input("\nPress Enter to exit...")

if __name__ == "__main__":
    main()